version: "3.9"

services:
  # ---------------- INFRA ----------------
  postgres:
    image: postgres:15-alpine
    container_name: proppio_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-proppio_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # Solo accesible v√≠a SSH tunnel
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: proppio_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: proppio_minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio_data:/data
    networks:
      - app_network

  dozzle:
    image: amir20/dozzle:latest
    container_name: proppio_dozzle
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle_data:/data
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_AUTH_PROVIDER: simple
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    networks:
      - app_network

  # ---------------- APPS ----------------
  api:
    container_name: proppio_api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .env
      - .env.production
      - .env.keys
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-proppio_db}
      REDIS_HOST: redis
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_PUBLIC_ENDPOINT: https://s3.betancur.work
      STORAGE_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      STORAGE_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      CORS_ORIGIN: http://localhost,https://app.tusass.com
      JWT_SECRET: ${JWT_SECRET:-supersecret}
      PUBLIC_API_URL: ${PUBLIC_API_URL:-https://api.tusass.com}
      MIKRO_ORM_USE_TS_NODE: "false"
    networks:
      - app_network

  web:
    container_name: proppio_web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    depends_on:
      - api
    expose:
      - "80"
    networks:
      - app_network

  # --------------- PROXY ----------------
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proppio_nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - app_network

# ---------------- VOLUMES ----------------
volumes:
  postgres_data:
  redis_data:
  minio_data:
  npm_data:
  npm_letsencrypt:
  dozzle_data:

    # ---------------- SECRETS ----------------
secrets:
  dozzle_users:
    file: ./files/dozzle/users.yml

# ---------------- NETWORK ----------------
networks:
  app_network:
    driver: bridge
